default:
  workspace: shared

stages:
- Build
- Test

jobs:
- name: RecipeConfig
  stage: Build
  use: PHPTest@1.0.0
  with:
    privateKey: this_is_private_key
    hostIP: this is host IP
    only:
      branches: master
    except:
      events:
      - tag

- name: Sleep
  stage: Build
  image: alpine
  workspace: shared
  script:
  - sleep 10

- name: Wake up
  stage: Build
  image: alpine
  workspace: none
  script:
  - echo Hello

- name: Sleep again
  stage: Build
  image: alpine
  script:
  - sleep 10

- name: Sleep more
  stage: Test
  image: alpine
  script:
  - sleep 10
  
- name: PHP CodeSniffer
  stage: Test
  image: sunasteriskrnd/php-workspace:7.4
  script:
  - composer sniff -d api

- name: Say bye!
  stage: Test
  image: alpine
  workspace: none
  script:
  - sleep 10
  - echo Byeee!

- name: Say bye again!
  stage: Test
  image: alpine
  script:
  - sleep 10
  - echo Byeee!
